# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('extension', models.CharField(choices=[('JPEG', 'jpeg'), ('PNG', 'png')], default='JPEG', max_length=4)),
                ('image', models.FileField(null=True, upload_to='img/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='TypeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='type_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_page.TypeImage'),
        ),
    ]
